apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - adapter-deployment.yaml
  - adapter-service.yaml
  - webui-deployment.yaml
  - webui-service.yaml
  - cloudflared-deployment.yaml
